name: Node.js
variations:

  - id: basic
    name: Basic Node.js App
    description: Simple Node.js applications
    files:
      - dockerfile
      - dockerignore
    variables:
      - name:  'NODE_VERSION'
        value: '14.5.0'
      - name:  'DEFAULT_ENV'
        value: 'production'
      - name:  'PORT'
        value: '8080'
      - name:  'APP_ENTRYPOINT'
        value: 'index.js'

